### ISSUE TITLE
Wrong number of layers are re-initialized in Baseline?

### ISSUE THREAD

**Issue by dorimedini** [dorimedini/kardashigans#26]
We should be training `mnist` and `cifar10` on FC networks with an input node layer, output node layer and three node inner layers. That should be 4 parameter layers, right? So why are only 3 being analyzed in phases 1 and 2 of Baseline?

**Comment by dorimedini** [comment]
On further inspection, if `n_layers` is 3 then the resulting topology will have 1 input layer, 2 inner layers and 1 output layer... desired behavior?

**Comment by galshachaf** [comment]
nope, input layer doesn't have weights
